image: 
  file: .gitpod.dockerfile
  
vscode:
  extensions:
    - elixir-lsp.elixir-ls@0.6.2:j/OgOgkgo0QJRBdZXhmoUQ==

ports:
  - port: 4000-4010

# Commands to start on workspace startup
tasks:
  - init: init DB and library
    command: init.sh