# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    if: github.ref == 'refs/heads/main' # Only run this job if it is on the master branch
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8.16
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.16
      - uses: actions/checkout@v2
        with:
          ref: main # Checkout out master instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch
      - uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: timely-green-nyala # Feel free to also put this in your secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MIGRATIONS: false # defaults to true
